/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.39
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AddressRequest } from './address-request';
import { ContactinformationsRequest } from './contactinformations-request';
import { EmailRequest } from './email-request';
import { PhoneRequest } from './phone-request';
import { WebsiteRequest } from './website-request';

/**
 * @type ContactinformationsRequestCompound
 * A Contactinformations Object and children to create a complete structure
 * @export
 */
export type ContactinformationsRequestCompound = ContactinformationsRequest;



