/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EzsigndocumentRequest } from './ezsigndocument-request';
import { EzsigndocumentRequestCompound } from './ezsigndocument-request-compound';


import Joi from 'joi';
import { ModelSchema } from '../base'

/**
 * Request for the /1/object/ezsigndocument/createObject API Request
 * @export
 * @interface EzsigndocumentCreateObjectV1Request
 */
export interface EzsigndocumentCreateObjectV1Request {
    /**
     * 
     * @type {EzsigndocumentRequest}
     * @memberof EzsigndocumentCreateObjectV1Request
     */
    objEzsigndocument?: EzsigndocumentRequest;
    /**
     * 
     * @type {EzsigndocumentRequestCompound}
     * @memberof EzsigndocumentCreateObjectV1Request
     */
    objEzsigndocumentCompound?: EzsigndocumentRequestCompound;
}

/**
 * A EzsigndocumentCreateObjectV1Request Schema
 * @export
 * @class EzsigndocumentCreateObjectV1RequestSchema
 */
export class EzsigndocumentCreateObjectV1RequestSchema extends ModelSchema {
    schema = {
        objEzsigndocument: Joi.any(),
        objEzsigndocumentCompound: Joi.any(),
    }
}



