/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




import Joi from 'joi';
import { ModelSchema } from '../base'

/**
 * Payload for the /1/object/ezsignfoldersignerassociation/createObject API Request
 * @export
 * @interface EzsignfoldersignerassociationCreateObjectV1ResponseMPayload
 */
export interface EzsignfoldersignerassociationCreateObjectV1ResponseMPayload {
    /**
     * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
     * @type {Array<number>}
     * @memberof EzsignfoldersignerassociationCreateObjectV1ResponseMPayload
     */
    a_pkiEzsignfoldersignerassociationID: Array<number>;
}

/**
 * A EzsignfoldersignerassociationCreateObjectV1ResponseMPayload Schema
 * @export
 * @class EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadSchema
 */
export class EzsignfoldersignerassociationCreateObjectV1ResponseMPayloadSchema extends ModelSchema {
    schema = {
        a_pkiEzsignfoldersignerassociationID: Joi.any().required(),
    }
}



