/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonAudit } from './common-audit';
import { EzsignfolderResponse } from './ezsignfolder-response';
import { FieldEEzsignfolderSendreminderfrequency } from './field-eezsignfolder-sendreminderfrequency';
import { FieldEEzsignfolderStep } from './field-eezsignfolder-step';


/**
 * @type EzsignfolderResponseCompound
 * An Ezsignfolder Object and children to create a complete structure
 * @export
 */
export type EzsignfolderResponseCompound = EzsignfolderResponse;



