/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




import Joi from 'joi';
import { ModelSchema } from '../base'

/**
 * Response for the /1/customer/{pksCustomerCode}/endpoint API Request
 * @export
 * @interface GlobalCustomerGetEndpointV1Response
 */
export interface GlobalCustomerGetEndpointV1Response {
    /**
     * The endpoint\'s URL
     * @type {string}
     * @memberof GlobalCustomerGetEndpointV1Response
     */
    sEndpointURL: string;
}

/**
 * A GlobalCustomerGetEndpointV1Response Schema
 * @export
 * @class GlobalCustomerGetEndpointV1ResponseSchema
 */
export class GlobalCustomerGetEndpointV1ResponseSchema extends ModelSchema {
    schema = {
        sEndpointURL: Joi.string().required(),
    }
}



