/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldEUserTypeSSPR } from './field-euser-type-sspr';


import Joi from 'joi';
import { ModelSchema } from '../base'

/**
 * Request for the /1/module/sspr/validateToken API Request
 * @export
 * @interface SsprValidateTokenV1Request
 */
export interface SsprValidateTokenV1Request {
    /**
     * The customer code assigned to your account
     * @type {string}
     * @memberof SsprValidateTokenV1Request
     */
    pksCustomerCode: string;
    /**
     * The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|
     * @type {number}
     * @memberof SsprValidateTokenV1Request
     */
    fkiLanguageID: number;
    /**
     * 
     * @type {FieldEUserTypeSSPR}
     * @memberof SsprValidateTokenV1Request
     */
    eUserTypeSSPR: FieldEUserTypeSSPR;
    /**
     * The email address.
     * @type {string}
     * @memberof SsprValidateTokenV1Request
     */
    sEmailAddress?: string;
    /**
     * The Login name of the User.
     * @type {string}
     * @memberof SsprValidateTokenV1Request
     */
    sUserLoginname?: string;
    /**
     * Hex Encoded Secret SSPR token
     * @type {string}
     * @memberof SsprValidateTokenV1Request
     */
    binUserSSPRtoken: string;
}

/**
 * A SsprValidateTokenV1Request Schema
 * @export
 * @class SsprValidateTokenV1RequestSchema
 */
export class SsprValidateTokenV1RequestSchema extends ModelSchema {
    schema = {
        pksCustomerCode: Joi.string().required().max(6).min(2),
        fkiLanguageID: Joi.number().required(),
        eUserTypeSSPR: Joi.any().required(),
        sEmailAddress: Joi.string(),
        sUserLoginname: Joi.string(),
        binUserSSPRtoken: Joi.string().required(),
    }
}



