/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.39
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/global-customer-api';
export * from './api/module-sspr-api';
export * from './api/module-user-api';
export * from './api/object-activesession-api';
export * from './api/object-apikey-api';
export * from './api/object-ezsigndocument-api';
export * from './api/object-ezsignfolder-api';
export * from './api/object-ezsignfoldersignerassociation-api';
export * from './api/object-ezsignsignature-api';
export * from './api/object-franchisebroker-api';
export * from './api/object-franchiseoffice-api';
export * from './api/object-franchisereferalincome-api';
export * from './api/object-period-api';

