/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApikeyRequest } from './apikey-request';
import { MultilingualApikeyDescription } from './multilingual-apikey-description';

/**
 * @type ApikeyRequestCompound
 * An Apikey Object and children to create a complete structure
 * @export
 */
export type ApikeyRequestCompound = ApikeyRequest;



