/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonAudit } from './common-audit';
import { MultilingualApikeyDescription } from './multilingual-apikey-description';

/**
 * An Apikey Object
 * @export
 * @interface ApikeyResponse
 */
export interface ApikeyResponse {
    /**
     * 
     * @type {MultilingualApikeyDescription}
     * @memberof ApikeyResponse
     */
    objApikeyDescription: MultilingualApikeyDescription;
    /**
     * The secret token for the API key.  This will be returned only on creation.
     * @type {string}
     * @memberof ApikeyResponse
     */
    sComputedToken?: string;
    /**
     * The unique ID of the Apikey
     * @type {number}
     * @memberof ApikeyResponse
     */
    pkiApikeyID: number;
    /**
     * 
     * @type {CommonAudit}
     * @memberof ApikeyResponse
     */
    objAudit: CommonAudit;
}


