/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonGetAutocompleteV1ResponseMPayload } from './common-get-autocomplete-v1-response-mpayload';
import { CommonResponse } from './common-response';
import { CommonResponseObjDebug } from './common-response-obj-debug';
import { CommonResponseObjDebugPayload } from './common-response-obj-debug-payload';

/**
 * @type CommonGetAutocompleteV1Response
 * Response for the /1/object/xxx/getAutocomplete API Request
 * @export
 */
export type CommonGetAutocompleteV1Response = CommonResponse;



