/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContactRequest } from './contact-request';
import { ContactRequestCompoundAllOf } from './contact-request-compound-all-of';
import { ContactinformationsRequestCompound } from './contactinformations-request-compound';

/**
 * @type ContactRequestCompound
 * A Contact Object and children to create a complete structure
 * @export
 */
export type ContactRequestCompound = ContactRequest & ContactRequestCompoundAllOf;



