/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EzsignfolderRequest } from './ezsignfolder-request';

/**
 * Request for the /1/object/ezsignfolder/editObject API Request
 * @export
 * @interface UNUSEDEzsignfolderEditObjectV1Request
 */
export interface UNUSEDEzsignfolderEditObjectV1Request {
    /**
     * 
     * @type {EzsignfolderRequest}
     * @memberof UNUSEDEzsignfolderEditObjectV1Request
     */
    objEzsignfolder?: EzsignfolderRequest;
}


