/* tslint:disable */
/* eslint-disable */
/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AttemptResponse } from './attempt-response';
import { CommonWebhook } from './common-webhook';
import { UserResponse } from './user-response';
import { WebhookResponse } from './webhook-response';
import { WebhookUserUserCreatedAllOf } from './webhook-user-user-created-all-of';

/**
 * @type WebhookUserUserCreated
 * This is the base Webhook object
 * @export
 */
export type WebhookUserUserCreated = CommonWebhook & WebhookUserUserCreatedAllOf;



